user1 = User.create(email: "gwendolyn@gardens.ca")
user2 = User.create(email: "urbanfarmer@goodearth.com")
user3 = User.create(email: "timothy@mail.com")
user4 = User.create(email: "edibleflowers@mail.com")
user5 = User.create(email: "annlovesplants@greenthumb.ca")

Favorite.create(user_id: 1, space_id: 2)
Favorite.create(user_id: 1, space_id: 4)
Favorite.create(user_id: 1, space_id: 6)
Favorite.create(user_id: 1, space_id: 7)
Favorite.create(user_id: 1, space_id: 8)
Favorite.create(user_id: 2, space_id: 3)
Favorite.create(user_id: 2, space_id: 5)
Favorite.create(user_id: 2, space_id: 7)
Favorite.create(user_id: 3, space_id: 1)
Favorite.create(user_id: 3, space_id: 2)
Favorite.create(user_id: 3, space_id: 8)
Favorite.create(user_id: 4, space_id: 4)
Favorite.create(user_id: 4, space_id: 5)
Favorite.create(user_id: 4, space_id: 6)
Favorite.create(user_id: 5, space_id: 7)
Favorite.create(user_id: 5, space_id: 8)

Space.create(user: user1, unit_number: "5", street_address: "1560 Ridge St", province: "BC", postal_code: "V5T 1J8", country: "Canada", square_meters: 15, outdoors: true, city: "Vancouver")
Space.create(user: user1, street_address: "271 Grant St", province: "BC", postal_code: "V5T 1M2", country: "Canada", square_meters: 10, outdoors: true, city: "Vancouver")
Space.create(user: user2, unit_number: "4", street_address: "448 10th Ave", province: "BC", postal_code: "V7L 3G2", country: "Canada", square_meters: 6, outdoors: true, city: "Vancouver")
Space.create(user: user3, unit_number: "2A", street_address: "978 Mumbleton Road", province: "BC", postal_code: "V2C 1M8", country: "Canada", square_meters: 25, outdoors: true, city: "Burnaby")
Space.create(user: user4, street_address: "23 Queensfield Drive", province: "BC", postal_code: "V1N 3G4", country: "Canada", square_meters: 12, outdoors: true, description: "One side of our garden plot is sunny and dry, while the other side gets more shade and tends to be wetter.", city: "New West")
Space.create(user: user5, unit_number: "6", street_address: "571 Denman", province: "BC", postal_code: "V3E 7G6", country: "Canada", square_meters: 1.55, outdoors: true, description: "We have a small patch of earth and we would love to see some plants growing in it!", city: "Vancouver")
Space.create(user: user5, street_address: "21 Brickmans Way", province: "BC", postal_code: "V1R 3G7", country: "Canada", square_meters: 40, outdoors: true, description: "I have lots of space for flowers and vegetables. A small stream runs through the middle. If you're inspired to do some landscaping as well, let me know as I have some experience with stonework.", city: "North Vancouver")
Space.create(user: user5, unit_number: "303", street_address: "971 Thurlow St", province: "BC", postal_code: "V9A 4B3", country: "Canada", square_meters: 2.5, outdoors: false, description: "I have a sun room that gets quite hot in the summer. I've always wanted to turn it into a greenhouse. Would you like to work with me on this project?", city: "Vancouver")

